### ISSUE TITLE
Implement time

### ISSUE THREAD

**Issue by GrayJack** [GrayJack/coreutils#53]
This is a tracking issue for the `time` utility.

### Required options and flags in the POSIX standard:

- [ ] `p` (long: `posix`, alias: `portability`)

### Required extension options and flags:

- [ ] `l` (long: `rusage`)
- [ ] `o` (long: `output`)
- [ ] `a` (long: `append`, requires: `o`)

**Notes:**
¹ : Long name not defined on other implementation of this utility. Implementer must choose a long name.
² : Short name (one letter) not defined on other implementation of this utility. Implementer must choose. a short name

### References

[POSIX standard text](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/time.html)
[FreeBSD Manual](https://www.freebsd.org/cgi/man.cgi?query=time&apropos=0&sektion=1&manpath=FreeBSD+13.0-current&arch=default&format=html)
[NetBSD Manual](https://man.netbsd.org/time.1)
[OpenBSD Manual](https://man.openbsd.org/time)
[DragonFlyBSD Manual](https://leaf.dragonflybsd.org/cgi/web-man?command=time&section=ANY)

### Unresolved questions:

Each time implementation has some unique extensions. One may need one of those in their respective system.

**Comment by envp** [comment]
Posting TODO here from #141:

Compatibility so far for `time.1`:

- [x] [POSIX.2](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/time.html)
- [x] [MacOS](https://ss64.com/osx/time.html)
- [x] [Linux WITHOUT GNU extensions](https://man7.org/linux/man-pages/man1/time.1.html)
- [x] [Linux GNU extensions](https://man7.org/linux/man-pages/man1/time.1.html)
- [x] [FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=time)
- [x] [NetBSD](https://man.netbsd.org/time.1)
- [x] [OpenBSD](https://man.openbsd.org/time.1)
- [x] [DragonflyBSD](https://man.dragonflybsd.org/?command=time&section=1)
- [x] [Illumos](https://illumos.org/man/1/time)
- [x] [Solaris](https://docs.oracle.com/cd/E26502_01/html/E29030/time-1.html#scrolltoc)
- [x] Fuchsia: No getrusage syscall

**Comment by envp** [comment]
#144 adds features from BSD `time` commands. `-l` is still unimplemented, as that requires some more work on macos (discussed on the PR)
